### ISSUE TITLE
Make a Glide app

### ISSUE THREAD

**Issue by AnthonyMastrean** [SummitRoute/aws_breaking_changes#10]
There's an awesome new site for making mobile apps from Google sheets.

https://www.glideapps.com/

I sketched an initial spreadsheet and app (this is not my area 😅).

 * [Google sheet](https://docs.google.com/spreadsheets/d/1U_zJRMNqPinKOhgOO3xTGVTeVHiZGcc0UrWaIP0ZVoo/edit?usp=sharing)
 * [Glide app design](https://go.glideapps.com/play/pEZQhFUXMfg7oHfjXbmn)
 * [Glide app preview](https://awsbreakingchanges.glideapp.io/)

Anyway, just thought this format was _perfect_ for the data you're collecting. Sure, the full desktop web experience is nice... I wonder if you can easily exchange data between a GitHub repo (or GitHub pages site) and a Google sheet?

**Comment by 0xdabbad00** [comment]
This is way outside of the scope of my goals for this project, and there aren't enough issues listed (and hopefully won't be many more) to warrant creating an app for someone to check regularly.  You're welcome to pull the content/fork this as needed if you wanted to do that though.
