### ISSUE TITLE
Discontinuing support for AWS App Mesh, effective September 30th, 2026

### ISSUE THREAD

**Issue by stewartcampbell** [SummitRoute/aws_breaking_changes#109]
https://aws.amazon.com/blogs/containers/migrating-from-aws-app-mesh-to-amazon-ecs-service-connect/

> After careful consideration, we have made the decision to discontinue support for AWS App Mesh, effective September 30th, 2026. Until this date, existing AWS App Mesh customers will be able to use the service as normal, including creating new resources and onboarding new accounts via the AWS CLI and AWS CloudFormation. Additionally, AWS will continue to provide critical security and availability updates to AWS App Mesh during this period. However, starting from September 24th, 2024, new customers will be unable to onboard to AWS App Mesh.

**Comment by 0xdabbad00** [comment]
Woah, thank you @stewartcampbell !
