### ISSUE TITLE
NICE EnginFrame discontinuation 

### ISSUE THREAD

**Issue by stknohg** [SummitRoute/aws_breaking_changes#110]
Found this along with the NICE DCV renaming.

* https://aws.amazon.com/jp/about-aws/whats-new/2024/10/nice-dcv-amazon-dcv-20240-ubuntu-2404/

> End of support notice: On 9/25/2025, AWS will discontinue for NICE EnginFrame. After 9/25/2025, new customer sign-ups and product upgrades are no longer available for NICE EnginFrame.

* https://aws.amazon.com/hpc/enginframe/
* https://aws.amazon.com/jp/blogs/hpc/discontinuation-of-nice-enginframe-effective-september-25th-2025/

**Comment by 0xdabbad00** [comment]
Thank  you @stknohg !
