### ISSUE TITLE
End of Life Notice EC2 G3 Instances

### ISSUE THREAD

**Issue by gear0** [SummitRoute/aws_breaking_changes#114]
Amazon will retire EC2 G3 by October 31, 2025.

The following notice reached me today:

We first launched the EC2 G3 instances (“G3 instances”) in July 2017, and have continued to provide customers a scalable AWS experience on the G3 instances since then. However, we can no longer continue to offer the high level of elasticity you have come to expect on the G3 instance family and are therefore working with customers to migrate their workloads to newer generation G instances by October 31, 2025. To learn more about these newer instances, see Amazon EC2 Instance types [1].

Existing users of G3 instances will see no change in their experience leading up to the retirement date of October 31, 2025. However, starting January 1, 2025, customers will no longer be able to purchase new Reserved Instances (RI) or Instance Savings Plans (SP) for G3 instances. Going forward, only existing G3 customers who have run G3 instances anytime in the past 12 months can restart or launch new G3 instances.

FAQs

Why is the G3 instance no longer supported?
- Amazon EC2 provides customers a scalable and reliable experience. G3 instance is not supported because we can no longer continue to offer the high level of elasticity you have come to expect on the G3 instance family.

What do I need to do?
- You are expected to migrate to newer generation G instances by October 31, 2025. Newer generation instances typically offer better price-performance than older generation instances.

Who will have access to the G3 instances going forward?
- Only existing G3 customers who have run G3 instances anytime in the past 12 months can restart or launch new G3 instances.

What happens to my existing RIs and SPs?
- You can exchange G3 Convertible Reserved Instances (CRI) with any other EC2 instance CRI using the Amazon EC2 console or command line tool by October 31, 2025. For G3 CRI, we recommend exchanging with newer generation G instances CRI. For G3 Standard Reserved Instances or G3 Instance Savings Plans with an expiration date after October 31, 2025, you can reach out to Customer Service through AWS Support center to request cancellation and pro-rated refunds.

Can I purchase new RIs and SPs?
- You cannot purchase new Standard Reserved Instances and Instance Savings Plan for G3 instances starting January 1, 2025. New Convertible Reserved Instances and Compute Savings Plan will not be applicable for G3 instances starting January 1, 2025.

If you have any questions or concerns please reach out to your Account Team or AWS Customer Support [2].

[1] https://aws.amazon.com/ec2/instance-types/#Accelerated_Computing
[2] https://aws.amazon.com/support

Sincerely,
Amazon Web Services

**Comment by art-stankov** [comment]
@0xdabbad00

**Comment by 0xdabbad00** [comment]
Hmm, I was hoping AWS would provide a page somewhere that I could reference that mentions the dates for retirement of different instance families, but it doesn't look like it exists, so I've added this via https://github.com/SummitRoute/aws_breaking_changes/commit/ede9861f5b5458464a749a8046d666a663729501

**Comment by 0xdabbad00** [comment]
Thank you @gear0! (and @art-stankov for the reminder)
