### ISSUE TITLE
Comprehend Medical API Changes

### ISSUE THREAD

**Issue by iann0036** [SummitRoute/aws_breaking_changes#28]
E-mail from AWS:
--
You are receiving this email because you have used Amazon Comprehend Medical. This email is to inform you of recent changes to the service that will impact functionality.

We recently launched a new API, DetectEntitiesV2 to replace the current DetectEntities API. We created DetectEntities V2 so that we can release new features in a backwards compatible way, allowing you to enjoy new features without additional development effort. We encourage you to update to DetectEntitiesV2 as soon as possible, as all of our upcoming features and accuracy improvements will only apply to DetectEntitiesV2. There are only two non-backwards-compatible changes from the original API. These are listed in the changelist and documentation below. In the meantime, the DetectEntities API will continue to operate as usual.

DetectEntitiesV2 Documentation: https://docs.aws.amazon.com/comprehend/latest/dg/API_hera_DetectEntitiesV2.htmlDetectEntitiesV2 and DetectEntities changelist:
* Acuity changed from Entity to Attribute
* Direction changed from Entity to Attribute

**Comment by 0xdabbad00** [comment]
It doesn't look like there is a deprecation date, other than I guess currently it has already been deprecated in the sense that it won't receive updates.  I want to wait until there is a deprecation date set before I add this.

**Comment by 0xdabbad00** [comment]
I'm closing this as it doesn't look like we're going to get a deprecation date set.
