### ISSUE TITLE
Botocore Vendored Requests

### ISSUE THREAD

**Issue by iann0036** [SummitRoute/aws_breaking_changes#29]
See: https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/

**Comment by 0xdabbad00** [comment]
My gut feeling is that I don't think this is going to have much of an impact, but it seems AWS is worried enough about it that they wrote a blog post, so I'll add it.

**Comment by 0xdabbad00** [comment]
Oh, looks like they already did this on October 21.  As it happened in the past, I'll leave this off.

**Comment by mwarkentin** [comment]
@0xdabbad00 according to [this](https://aws.amazon.com/blogs/compute/upcoming-changes-to-the-python-sdk-in-aws-lambda/) they will be removing the vendored `requests` library from python lambdas on March 30, 2020. Does that classify?
