### ISSUE TITLE
S3 Buckets with non DNS-compliant names in us-east-1

### ISSUE THREAD

**Issue by xose** [SummitRoute/aws_breaking_changes#3]
This one was already changed last year, but might still be relevant with the upcoming S3 changes to path-style requests:

> On March 1, 2018, we updated our naming conventions for S3 buckets in the US East (N. Virginia) Region to match the naming conventions that we use in all other worldwide AWS Regions. Amazon S3 no longer supports creating bucket names that contain uppercase letters or underscores. This change ensures that each bucket can be addressed using virtual host style addressing, such as https://myawsbucket.s3.amazonaws.com. We highly recommend that you review your existing bucket-creation processes to ensure that you follow these DNS-compliant naming conventions.

https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#non-dns-compliant-bucketname-challenges

**Comment by gitrc** [comment]
thanks for this.

**Comment by 0xdabbad00** [comment]
I'm going to close this out as the change took place already, although it's impact wouldn't really be felt until the S3 path deprecation happens, which is no longer going to impact existing buckets.   Therefore I don't think is going to have an impact anymore.
