### ISSUE TITLE
RDS Postgresql 9.4 deprecation

### ISSUE THREAD

**Issue by mwarkentin** [SummitRoute/aws_breaking_changes#30]
Hello,

The notification that was sent on August 5th, 2019 had some incorrect dates. Please discard that notice and use this  instead. We apologize for the inconvenience it has caused.

This is to notify you that, following the PostgreSQL community deprecation plan for 9.4 in February 2020, Amazon RDS will be discontinuing support for PostgreSQL version 9.4 in RDS, starting January 15, 2020.

Amazon RDS has been supporting the PostgreSQL major version 9.4 since 2015. That release has since been replaced by subsequent major versions that contain significant improvements in functionality, security, reliability, and performance. The PostgreSQL community has announced the end of life date for PostgreSQL 9.4 as February 2020 [1].  Aligning with the community support model, AWS will be ending support for the PostgreSQL major version 9.4 in Amazon RDS, including its minor engine versions including 9.4.1, 9.4.4, 9.4.5, 9.4.7, 9.4.9, 9.4.10, 9.4.11, 9.4.12, 9.4.14, 9.4.15, 9.4.17, 9.4.18, 9.4.19, 9.4.20, 9.4.21, and 9.4.23. We will continue to support 9.5 and more recent versions of the PostgreSQL database on Amazon RDS.

We recommend that you upgrade your Amazon RDS for PostgreSQL 9.4 database instances to version 9.6, 10, or 11 at your earliest convenience. You may also choose to upgrade to 9.5, but that version is scheduled for end of support in February 2021 [1]. Depending on your PostgreSQL 9.4 minor version and PostGIS extension usage, you may be able to upgrade directly to version 10 or 11 [2]. Alternatively, you can upgrade to one higher version at a time. For example, if you want to upgrade your 9.4 instance to version 10, first upgrade to 9.5, and then to 9.6, followed by an upgrade to 10. You can initiate an upgrade by going to the Modify DB Instance page in the AWS Management Console and changing the database version setting to a newer major version of PostgreSQL. If you choose the "Apply Immediately" option, the upgrade will be initiated immediately after exiting the Modify page. If you choose not to apply the change immediately, the upgrade will be performed during your subsequent maintenance window. To learn more about upgrading PostgreSQL major versions in RDS, review the Upgrading Database Versions page [2].

As part of the retirement plan for Amazon RDS PostgreSQL 9.4, starting September 15, 2019, we will be disabling creation of any new PostgreSQL 9.4 instances using the AWS console. Starting November 15, 2019, we will be performing forced auto minor version upgrades on your remaining 9.4 instances to the recent minor version of 9.4. You can continue to do PostgreSQL 9.4 restores and read replica creations until January 15, 2020. Starting  January 15, 2020, your remaining 9.4 instances will be force upgraded to the most recent minor version of PostgreSQL 11. If we are not able to upgrade to PostgreSQL 11 for any reason, we will upgrade to the 9.5 version. After that upgrade process is complete, any instance restored from a snapshot of PostgreSQL 9.4 version will automatically and immediately be upgraded to a currently supported version.
Your affected PostgreSQL 9.4 instances in the US-EAST-1 Region are listed below:

<list of rds instances>

If you have already upgraded your instance(s) to a higher version, no further action is required.
Should you have any questions or concerns, the AWS Support Team is available on the community forums and via Premium Support [3]. To learn more about Amazon RDS' policy for supporting database versions, please see [4].

[1] https://www.postgresql.org/support/versioning/
[2] http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html
[3] http://aws.amazon.com/support
[4] https://aws.amazon.com/rds/faqs/ [search for "guidelines for deprecating database engine versions"]

Sincerely,
Amazon Web Services
Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is a registered trademark of Amazon.com, Inc. This message was produced and distributed by Amazon Web Services Inc., 410 Terry Ave. North, Seattle, WA 98109-5210

**Comment by 0xdabbad00** [comment]
Thanks for this! I've added it and cut a new release. https://github.com/SummitRoute/aws_breaking_changes/releases/tag/2019-11-12

**Comment by danielcompton** [comment]
The title of the release doesn't seem quite accurate?

"RDS PostgreSQL 9.4 forced upgrade to PostgreSQL 11 on Jan 15, 2022"

but the notification only says:

> We recommend that you upgrade your Amazon RDS for PostgreSQL 9.4 database instances to version 9.6, 10, or 11 at your earliest convenience

**Comment by mwarkentin** [comment]
Forced upgrades will begin on Jan 15, 2020 according to the notification. 

> Starting January 15, 2020, your remaining 9.4 instances will be force upgraded to the most recent minor version of PostgreSQL 11. If we are not able to upgrade to PostgreSQL 11 for any reason, we will upgrade to the 9.5 version.

**Comment by danielcompton** [comment]
Oops, I didn't read far enough down the notification. Sorry!
