### ISSUE TITLE
Two mentions

### ISSUE THREAD

**Issue by wolruf** [SummitRoute/aws_breaking_changes#33]
I noticed Device Farm:
https://docs.aws.amazon.com/en_pv/devicefarm/latest/developerguide/history.html

and MFA via SMS (bottom of page):
https://aws.amazon.com/iam/features/mfa/

**Comment by TomDufall** [comment]
I can't see any future breaking changes mentioned at either of those locations. This repo primarily aims to document upcoming changes - it normally doesn't worry about recording historic changes.

**Comment by wolruf** [comment]
Understood, I thought the changes were recent enough (Devicefarm ending Direct Device Access on Sep 9th, 2019). MFA/SMS ending Feb 1st, 2019. Happy to close this.

**Comment by 0xdabbad00** [comment]
Thank you @wolruf and @TomDufall. Those are changes I should have identified in advance and documented, but in another recent discussion on twitter at https://twitter.com/0xdabbad00/status/1191777243728470016 I have decided that I don't want to record changes after the fact that could have, or did, break things for people.  So this repo is largely focused on letting people know about upcoming changes.
