### ISSUE TITLE
removal of SGE and Torque from ParallelCluster

### ISSUE THREAD

**Issue by cariaso** [SummitRoute/aws_breaking_changes#40]
https://github.com/aws/aws-parallelcluster/wiki/Deprecation-of-SGE-and-Torque-in-ParallelCluster

**Comment by 0xdabbad00** [comment]
Thanks for bringing this to my attention @cariaso.  It sounds like people with existing clusters can continue having their cluster run with these tools that are being sunset.  It's tough for me to decide what to include on this list, but I try to imagine if someone set something up a year ago, would it continue running?  Although there is a possibility that they set something up to auto-update, it seems like that existing cluster will keep running, so it's not going to break existing processes.
