### ISSUE TITLE
Fargate deprecation of platform 1.0 - 1.2

### ISSUE THREAD

**Issue by mwarkentin** [SummitRoute/aws_breaking_changes#41]
Not sure if this fits, it sounds like tasks can continue to launch but will no longer receive bug fixes and security fixes. 

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform-versions-retired.html

Force update date	
October 26, 2020	

Deprecation date 
December 14, 2020

**Comment by 0xdabbad00** [comment]
Nice find. It doesn't sound like they are breaking anything though as you pointed out it sounds like tasks will continue to launch, so I'm going to leave this off the list.
