### ISSUE TITLE
AWS Lambda retry behavior change

### ISSUE THREAD

**Issue by mwarkentin** [SummitRoute/aws_breaking_changes#48]
We are changing the way that asynchronous invocations of AWS Lambda functions work when the function has reserved concurrency set to zero. Previously, if the reserved concurrency was set to zero for such a function, the events sent to that function were retried for up to six hours, or a customer configured maximum number of attempts or event age, before being sent to the dead letter queue (DLQ) or on-failure event destination configured for that function. As of August 16, 2021, for functions with reserved concurrency set to zero, all events will be automatically sent to the configured DLQ or the on-failure event destination immediately, instead of being retried. Customers who wish to process events that were sent while reserved concurrency was set to zero will need to consume the events from the DLQ or on-failure event destination. This behavior will be enabled in all regions. Please refer to the AWS Lambda User Guide for information on how to configure a DLQ[1] or an on-failure event destination[2].

[1] https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html#dlq
[2] https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html#invocation-async-destinations

**Comment by 0xdabbad00** [comment]
Thank you. I've added it. I'm a little hesitant as it doesn't seem like it will actually break things for people and seems like a good thing to change, but it is a change that could impact people's assumptions and changes how existing infrastructure works.
