### ISSUE TITLE
Macie Classic and CloudTrail global events

### ISSUE THREAD

**Issue by iann0036** [SummitRoute/aws_breaking_changes#56]
Hello,

On November 22, 2021, Macie Classic alerts that derive from AWS CloudTrail global service events for AWS Identity and Access Management (IAM) and AWS Security Token Service (AWS STS) API calls will be retired (no longer generated) in the US-WEST-2 (Oregon) AWS Region. This is due to changes to how CloudTrail captures global service events. For more information, please refer to the Amazon Macie User Guide [1].

Macie Classic will continue to generate alerts for these events in the US-EAST-1 (N. Virginia) Region. If you are already using Macie Classic in that Region, you can continue to receive alerts for global service events outside the US-EAST-1 (N. Virginia) Region. To do this, use CloudTrail to convert your single-region trails that use global service events into multi-region trails, or create a single-region trail to subscribe to global service events in the US-EAST-1 (N. Virginia) Region. For more information, please refer to the Global service events [2] in the AWS CloudTrail User Guide.

If you have any questions or concerns, please reach out to AWS Support [3].

[1] https://docs.aws.amazon.com/macie/latest/userguide/macie-alerts.html
[2] https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-concepts.html#cloudtrail-concepts-global-service-events
[3] http://aws.amazon.com/support

Sincerely,
Amazon Web Services

**Comment by 0xdabbad00** [comment]
Thank you, I've added it.
