### ISSUE TITLE
lambda state change updates

### ISSUE THREAD

**Issue by kapilt** [SummitRoute/aws_breaking_changes#57]
lambda now requires waiting for functions to be ready before doing code or configuration changes, previously this only applied to vpc attached lambdas. this rolled out dec 5th, 2021, and could break applications directly provisioning/updating lambdas.

https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions

**Comment by 0xdabbad00** [comment]
Thank you! I've added it to the archive as by the time I got to this, the change had long since been put into effect.
