### ISSUE TITLE
Add Python 3.6 for lambda EOL

### ISSUE THREAD

**Issue by 0xdabbad00** [SummitRoute/aws_breaking_changes#61]
"""
Hello,

We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Python 3.6 runtime.

We are ending support for Python 3.6 in AWS Lambda. This follows Python 3.6 End-Of-Life (EOL) reached on December 23, 2021 [1].

As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting July 18, 2022, Lambda will no longer apply security patches and other updates to the Python 3.6 runtime used by Lambda functions, and functions using Python 3.6 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Python 3.6 runtime. Starting August 17, 2022, you will no longer be able to update existing functions using the Python 3.6 runtime.

We recommend that you upgrade your existing Python 3.6 functions to Python 3.9 before August 17, 2022.

End of support does not impact function execution. Your functions will continue to run. However, they will be running on an unsupported runtime which is no longer maintained or patched by the AWS Lambda team.

The following command shows how to use the AWS CLI [3] to list all functions in a specific region using Python 3.6. To find all such functions in your account, repeat this command for each region:

aws lambda list-functions --function-version ALL --region us-east-1 --output text --query "Functions[?Runtime=='python3.6'].FunctionArn"

If you have any concerns or require further assistance, please contact AWS Support [4].

[1] https://peps.python.org/pep-0494/
[2] https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html
[3] https://aws.amazon.com/cli/
[4] https://aws.amazon.com/support
"""

**Comment by 0xdabbad00** [comment]
Added in https://github.com/SummitRoute/aws_breaking_changes/commit/6629b60faccd8e6007bca99ebcc355ae20fc2d4b

**Comment by PatMyron** [comment]
`dotnetcore3.1` and `nodejs12.x` dates added as well:
https://github.com/aws-cloudformation/cfn-lint/pull/2327
https://github.com/terraform-linters/tflint-ruleset-aws/pull/362
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy

**Comment by 0xdabbad00** [comment]
Thanks, added in https://github.com/SummitRoute/aws_breaking_changes/commit/dd1cdd8bd479622297f6bf5da46dbbc210d8220e
