### ISSUE TITLE
AWS WorkSpaces Application Manager is Retiring

### ISSUE THREAD

**Issue by jason-riddle** [SummitRoute/aws_breaking_changes#67]
See https://aws.amazon.com/blogs/desktop-and-application-streaming/amazon-workspaces-application-manager-amazon-wam-is-retiring/

**Comment by 0xdabbad00** [comment]
Thank you! Added in https://github.com/SummitRoute/aws_breaking_changes/commit/d3103797948e970f124161312ba11149fe838b35
