### ISSUE TITLE
Node 12 Deprecation pushed back?

### ISSUE THREAD

**Issue by mattmapadmi** [SummitRoute/aws_breaking_changes#69]
Has the NodeJS 12 deprecation been delayed? I can't find the original announcement, and on the runtime page it says Mar 31 2023

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by 0xdabbad00** [comment]
Looks like you're right, it has been delayed. Here's an archived version of the link you gave from September showing NodeJS 12 was to be deprecated on Dec 14. https://web.archive.org/web/20220901052910/https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by 0xdabbad00** [comment]
The .NET Core 3.1 run-time EOL was also pushed back. I've updated table for both.  Thank you for spotting that.  https://github.com/SummitRoute/aws_breaking_changes/commit/8a049fa5e0c0e7a25483689bd5a539ac97709791
