### ISSUE TITLE
Atom feed not updating

### ISSUE THREAD

**Issue by mwebber** [SummitRoute/aws_breaking_changes#71]
The Atom feed does not appear to be updated any more - the most recent entry is for September 27, 2021.

It looks like the Atom feed simply reports repo tags/releases, and changes since then have not been tagged.
There are probably other ways (GitHub actions?) to generate an RSS or Atom feed.

**Comment by 0xdabbad00** [comment]
Thank you. I need to remember to tag the releases or in theory to automate the tagging.
