### ISSUE TITLE
DeepLens retiring

### ISSUE THREAD

**Issue by 0xdabbad00** [SummitRoute/aws_breaking_changes#72]
Corey Quinn posted this: https://awscommunity.social/@Quinnypig/109784554147152881
![image](https://user-images.githubusercontent.com/1979334/215807517-5ccd5014-1bb6-4af2-84a1-6f044abc0c5f.png)

DeepLens is being retired on Jan 31, 2024

**Comment by stefansundin** [comment]
@0xdabbad00 Why link to Corey's ~~tweet~~ toot and not the official page? https://docs.aws.amazon.com/deeplens/latest/dg/deeplens-end-of-life.html

And I don't think "including no longer having access to any DeepLens devices" is correct. They're shutting down the AWS service but I'm pretty sure you can have local SSH access to the device still, so it shouldn't be a complete brick. I'll be testing with my DeepLens later.

Hopefully they'll keep the AWS docs online even after the service is gone, as they host documentation on how to reset the device and none of it seems to require that the AWS service is online. https://docs.aws.amazon.com/deeplens/latest/dg/deeplens-troubleshooting-factory-reset.html

> You can set up your AWS DeepLens camera as a Linux computer using a pointer, keyboard, monitor, HDMI to micro HDMI cable, and a USB hub.

**Comment by 0xdabbad00** [comment]
I didn't know there was an official announcement yet. Thank you.  I've swapped out the link reference.

I'm not sure on how to interpret AWS's statement:
> Starting January 31, 2024, you can no longer access AWS DeepLens through the AWS management console, manage AWS DeepLens devices, or access any projects you have created.

My understanding of that line is that it is saying you cannot use the AWS console OR manage the devices through any means, but I guess a different way to understand that line is that you cannot manage the devices THROUGH the console.  Based on your link that devices can still be used for some purpose, maybe it's more correct to add "through AWS to my statement, so "including no longer having access to any DeepLens devices through AWS".  Would that be correct from your understanding?

**Comment by stefansundin** [comment]
I would just say something simple like "The AWS DeepLens service is shutting down". 🤷

It doesn't sound like they're locking everyone out of their devices, which would be quite evil. My experience has been that AWS hardware is fairly open and easily hackable. I think they're running some kind of Ubuntu flavor. I'm not an expert though so maybe someone else will chime in here with a better take. :)
