### ISSUE TITLE
CodeStar deprecation

### ISSUE THREAD

**Issue by iann0036** [SummitRoute/aws_breaking_changes#84]
Hello,

You are receiving this message because you have one or more AWS CodeStar projects that will be impacted by an upcoming change to the service.

On July 31, 2024, we will discontinue support for creating and viewing AWS CodeStar projects. After July 31, 2024, you will no longer be able to access the CodeStar console or create new projects. However, the AWS resources created by CodeStar, including your source repos, pipelines, and builds, will be unaffected by this change and will continue to function. AWS CodeStar connections will not be impacted by this discontinuation. 

If you wish to use blueprints to quickly start new projects, or easily invite developers with project-based permissions, Amazon CodeCatalyst provides a streamlined getting started process and additional functionality to manage your software projects. For more information on functionality and pricing of Amazon CodeCatalyst please refer to our documentation [1].

If you have questions or concerns, please reach out to AWS Support [2].

[1] https://codecatalyst.aws/explore
[2] https://aws.amazon.com/support

**Comment by moltar** [comment]
What about CodeStar GitHub connections for the Pipeline source?

**Comment by iann0036** [comment]
Per the above:

> AWS CodeStar connections will not be impacted by this discontinuation.

CodeStar GitHub connections are unaffected.
