### ISSUE TITLE
AWS Batch DescribeJobDefinition API breaking change

### ISSUE THREAD

**Issue by ArielPrevu3D** [SummitRoute/aws_breaking_changes#86]
Today AWS updated their API documentation for DescribeJobDefinition on AWS Batch. They added the `This parameter can't be used with other parameters.` to the `jobDefinitions` parameter, which wasn't there earlier this year.

Now: https://docs.aws.amazon.com/batch/latest/APIReference/API_DescribeJobDefinitions.html
Before: https://web.archive.org/web/20230323044216/https://docs.aws.amazon.com/batch/latest/APIReference/API_DescribeJobDefinitions.html

This broke our production application without warning. Does this qualify for this repository?

**Comment by 0xdabbad00** [comment]
Even though this was a change that did break your production workload, it sounds like this had been a bug they fixed, and seems too minor to include on this list next to entire services being shutdown.
