### ISSUE TITLE
ACP Deprecation

### ISSUE THREAD

**Issue by iann0036** [SummitRoute/aws_breaking_changes#87]
Hello,

AWS Application Cost Profiler (ACP) will be discontinued by 12/15/2023. We have noticed that even though you may have never used ACP, you have an ACP service configuration set up for your account. This configuration will be removed when ACP is discontinued. Please let us know if you have any questions or concerns with this change.

Sincerely,
AWS Application Cost Profiler Service Team.

**Comment by 0xdabbad00** [comment]
Looks like they bumped the data up to September 30, 2024 from the docs.  I'll get this added though. 
![image](https://github.com/SummitRoute/aws_breaking_changes/assets/1979334/a08db447-faa1-4af1-bce0-00c685334085)

**Comment by 0xdabbad00** [comment]
Resolved in https://github.com/SummitRoute/aws_breaking_changes/commit/c37cc790e8e2b88fcab32dce8d35c7d27fdeb872
