### ISSUE TITLE
Add Deprecated Lambda runtimes

### ISSUE THREAD

**Issue by iainelder** [SummitRoute/aws_breaking_changes#91]
You've got Python 3.6 in the archive. What about the next [deprecated Lambda runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)?

It's late for the Python 3.7 announcement, but we've got 2 weeks before the next round of deprecations.

|Name           |Identifier|Operating system|Deprecation date|Block function create|Block function update|
|---------------|----------|----------------|----------------|---------------------|---------------------|
|Java 8         |java8     |Amazon Linux    |Jan 8, 2024     |Feb 8, 2024          |Mar 12, 2024         |
|Go 1.x         |go1.x     |Amazon Linux    |Jan 8, 2024     |Feb 8, 2024          |Mar 12, 2024         |
|OS-only Runtime|provided  |Amazon Linux    |Jan 8, 2024     |Feb 8, 2024          |Mar 12, 2024         |
|Ruby 2.7       |ruby2.7   |Amazon Linux 2  |Dec 7, 2023     |Jan 9, 2024          |Feb 8, 2024          |
|Node.js 14     |nodejs14.x|Amazon Linux 2  |Dec 4, 2023     |Jan 9, 2024          |Feb 8, 2024          |
|Python 3.7     |python3.7 |Amazon Linux    |Dec 4, 2023     |Jan 9, 2024          |Feb 8, 2024          |

**Comment by iainelder** [comment]
@PatMyron , good idea.

The table of breaking changes still makes sense for each AWS feature whose lifecycle doesn't depend on third-party projects. AWS and its user community don't always agree on what counts as a "breaking change", especially on pricing changes.

Services such as Lambda and RDS are a transparent wrapper around other products with their own lifecycle. This repo doesn't need to be an exhaustive deprecation database for those. A list of all the AWS support calendars would already add a lot of value.

At least all the Lambda runtimes are listed in one place.

The same approach makes even more sense for RDS. Each engine tracks supported versions differently.

* [Aurora Versions](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.VersionPolicy.html)
* [PostgreSQL Release Calendars](https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-release-calendar.html)
* [Oracle Release Notes](https://docs.aws.amazon.com/AmazonRDS/latest/OracleReleaseNotes/Welcome.html)
* [MySQL Versions](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MySQL.Concepts.VersionMgmt.html)
* [MariaDB Versions](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MariaDB.Concepts.VersionMgmt.html)
* [SQL Server Versions](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_SQLServer.html)
* [Db2 Versions](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Db2.Concepts.VersionMgmt.html)

**Comment by iainelder** [comment]
@PatMyron I'd appreciate your review on my PR #92 to add the doc links to the readme.

**Comment by 0xdabbad00** [comment]
Resolved via #92 . Thank you.
