### ISSUE TITLE
Add price increase for Cognito

### ISSUE THREAD

**Issue by 0xdabbad00** [SummitRoute/aws_breaking_changes#94]
I'm not entirely sure what changed here (in terms of was this supposed to be free before or was just in beta and did not yet have pricing?), so needs review.

https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-cognito-tiered-pricing-m2m-usage/

**Comment by art-stankov** [comment]
@0xdabbad00 
<img width="387" alt="image" src="https://github.com/user-attachments/assets/3f55ec1d-f809-48cc-8329-2ad3b7c4bbbd">
Reply from AWS sales rep

**Comment by sbe-arg** [comment]
How is a cost change a breaking change?

**Comment by ciberado** [comment]
Imho an **increment** in cost has potentially the same effect that a change in the API: you will need to revisit the architecture.

**Comment by moltar** [comment]
Agreed, any change in the "contract" whether legal, explicit, implicit or otherwise is a breaking change.

**Comment by moltar** [comment]
Another way to think is: any **factual** changes that anyone had relied on to make downstream decisions is a breaking change.

**Comment by ashleykleynhans** [comment]
I disagree, I consider a "breaking change" to be something that will literally BREAK and stop working. Price increases don't break anything and stop things from working.

**Comment by MattiasEh** [comment]
I'm not commenting on this AWS Cognito price increase, specifically, but price increases absolutely can have massive impacts on architectures.  Take, for example, [Google's Multi-Region bucket price increase](https://cloud.google.com/storage/pricing-announce#replication) which destroyed the cost profile of systems making heavy writes to asia/asia1 multi-region buckets.  In the unlikely extreme (heavy writes of large short-lived objects), that change could have raised some bills from negligible to bankrupting.  I made [a video at that time](https://youtu.be/wm0FcuwMA14?t=211) saying:

> I find it a bit simpler to think of this sweeping set of price changes to multi-regions more like a service deprecation, really.  Google Cloud Storage Multi-Region Version 1 is end-of-life and going away, and the completely different Google Cloud Storage Multi-Region Version 2 will take its place on October 1st.  Different service, different pricing.  So, you should figure out what to do about your system's architecture and and make sure your data is somewhere that you'll be happy for it to live after that time.

Now that AWS has started breaking their longstanding assurances, they should receive the same critical review.

Historically, AWS prices always went _down_, and that direction never makes a particular architecture unprofitable—only maybe makes another option more preferable for future reconsideration.  But prices going _up_ is very different to me.

**Comment by 0xdabbad00** [comment]
Despite the name of this repo being called "aws_breaking_changes", the scope of the project expanded years ago to additionally include price increases on AWS as they are very rare.  You can see the readme.txt states this. 
![image](https://github.com/user-attachments/assets/8a7e7ba0-a9e0-43e2-8530-71a29b499c97)

The start of the readme makes an attempt and defining the scope of this repo, but it's sometimes just my personal preference.
