### ISSUE TITLE
Launch Configurations to de deprecated On October 1st 2024

### ISSUE THREAD

**Issue by jchrisfarris** [SummitRoute/aws_breaking_changes#95]
From my inbox (In Japanese & english)
> Hello,
> 
> In 2021, AWS announced the plan to deprecate launch configurations in favor of launch templates. Since that time, continual enhancements have been made to encourage migration to launch templates. This notification contains details about the next step in the launch configuration deprecation process.
> 
> Starting on October 1, 2024, you will be unable to create new launch configurations except in AWS Regions where you had a launch configuration in your AWS account or AWS Organizations at some point between July 1, 2024 and October 1, 2024.
> 
> Affected accounts will receive the following exception when trying to create a launch configuration through the API or CLI:
> 
> UnsupportedOperationException: The launch configuration creation operation is not available in your account. Use launch templates to create configuration templates for your Auto Scaling groups.
> 
> Prior to this step, we have already taken the following actions to begin deprecating launch configurations:
> 
> * Since January 1, 2023, launch configurations have not been updated with new instance types released after that date. Any new instance types that were released before January 1, 2023 in regions that became available after that date remain inaccessible through launch configurations. To use the latest instance types, users must transition to using launch templates.
> * Since January 1, 2023, launch configurations have not received any new EC2 feature updates. To use new EC2 features, users must now use launch templates.
> * Since April 1, 2023, new AWS accounts can no longer create launch configurations in the EC2 console. Only accounts created before this date retain access.
> 
> We strongly encourage the remaining customers of launch configurations to migrate to launch templates as soon as possible. Our documentation provides guidance on using the console migration tool to convert launch configurations to launch templates [1]. To identify Auto Scaling groups that are still using launch configurations, you can run this script [2].
> 
> If you have any questions or concerns, please reach out to AWS Support [3].
> 
> [1] https://docs.aws.amazon.com/autoscaling/ec2/userguide/migrate-to-launch-templates.html
> [2] https://github.com/aws-samples/amazon-ec2-auto-scaling-group-examples/tree/main/tools/launch-configuration-inventory
> [3] https://aws.amazon.com/support

**Comment by 0xdabbad00** [comment]
Thank you @jchrisfarris !
