### ISSUE TITLE
QLDB (Quantum Ledger Database)

### ISSUE THREAD

**Issue by PatMyron** [SummitRoute/aws_breaking_changes#96]
> Amazon QLDB is no longer available for new customer sign-ups

https://aws.amazon.com/qldb/

> End of support notice: Existing customers will be able to use Amazon QLDB until end of support on 07/31/2025

https://docs.aws.amazon.com/qldb/latest/developerguide/document-history.html

**Comment by 0xdabbad00** [comment]
Thank you @PatMyron !
