### ISSUE TITLE
SimpleDB isn't available in new regions

### ISSUE THREAD

**Issue by xssfox** [SummitRoute/aws_breaking_changes#98]

**Comment by 0xdabbad00** [comment]
I'm going to avoid adding service that aren't growing.  There are a number of services that haven't reached all regions, or some that remain in only one region (ex. Device Farm in us-west-2).  These services may one day expand, so I don't want to mark them as deprecated.

**Comment by ashemedai** [comment]
@0xdabbad00 They won't. See [Jeff Barr on X](https://mastodon.social/@asmodai/112881180944377262). (Or via [my repost on Fedi](https://mastodon.social/@asmodai/112881180944377262))

Essentially they will stop onboarding of new customers on S3 Select, CloudSearch, Cloud9, SimpleDB, Forecast, Data Pipeline, and CodeCommit.

**Comment by 0xdabbad00** [comment]
The deprecations that have occurred this week that Jeff Barr mentioned are different than the situation with SimpleDB, and will be added shortly.

**Comment by 0xdabbad00** [comment]
Oh, I just realized Jeff Barr did mention SimpleDB too!

**Comment by ashemedai** [comment]
@0xdabbad00 Thanks!
